version: '3.8'

services:
  boxarr:
    image: boxarr/boxarr:latest
    container_name: boxarr
    
    environment:
      # Timezone
      - TZ=${TZ:-America/New_York}
      
      # Radarr connection (required)
      - BOXARR_RADARR__CONNECTION__URL=${RADARR_URL:-http://radarr:7878}
      - BOXARR_RADARR__CONNECTION__API_KEY=${RADARR_API_KEY}
      
      # Optional overrides
      - BOXARR_RADARR__MOVIES__ROOT_FOLDER=${MOVIES_ROOT:-/movies}
      - BOXARR_BOXARR__UI__THEME=${UI_THEME:-purple}
      - BOXARR_LOGGING__LEVEL=${LOG_LEVEL:-INFO}
    
    volumes:
      # Configuration and data persistence
      - ./config:/config
      - ./data:/data
      
      # Optional: Share timezone from host
      - /etc/localtime:/etc/localtime:ro
    
    ports:
      - "${WEB_PORT:-8888}:8888"    # Web interface
      - "${API_PORT:-8889}:8889"    # API
    
    networks:
      - media
    
    restart: unless-stopped
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    labels:
      # Traefik labels (optional)
      - "traefik.enable=true"
      - "traefik.http.routers.boxarr.rule=Host(`boxarr.${DOMAIN}`)"
      - "traefik.http.services.boxarr.loadbalancer.server.port=8888"
      
      # Homepage labels (optional)
      - "homepage.group=Media"
      - "homepage.name=Boxarr"
      - "homepage.icon=boxarr.png"
      - "homepage.href=http://boxarr:8888"
      - "homepage.description=Box Office Tracking"

  # Example Radarr service (optional)
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
    
    volumes:
      - ./radarr/config:/config
      - ${MOVIES_PATH:-./movies}:/movies
      - ${DOWNLOADS_PATH:-./downloads}:/downloads
    
    ports:
      - "7878:7878"
    
    networks:
      - media
    
    restart: unless-stopped

# Networks
networks:
  media:
    name: media
    driver: bridge

# Example .env file content:
# RADARR_API_KEY=your_radarr_api_key_here
# RADARR_URL=http://radarr:7878
# MOVIES_ROOT=/movies
# UI_THEME=purple
# LOG_LEVEL=INFO
# WEB_PORT=8888
# API_PORT=8889
# TZ=America/New_York
# DOMAIN=example.com
# MOVIES_PATH=/path/to/movies
# DOWNLOADS_PATH=/path/to/downloads