name: CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tags: ${{ steps.meta.outputs.tags }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
        labels: |
          org.opencontainers.image.title=Boxarr
          org.opencontainers.image.description=Box Office Tracking for Radarr
          org.opencontainers.image.vendor=Boxarr Project
          org.opencontainers.image.licenses=GPL-3.0
          
    - name: Build and push Docker images
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: true
        sbom: true
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build.outputs.digest }}
        push-to-registry: true

  security-scan:
    name: Security Scan Docker Image
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      security-events: write
      
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push.outputs.image-digest }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Run Trivy vulnerability scanner (table format)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push.outputs.image-digest }}
        format: 'table'

  test-deployment:
    name: Test Docker Deployment
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
    - name: Test GitHub Container Registry image
      run: |
        docker run --rm -d --name boxarr-test \
          -p 8888:8888 \
          -v /tmp/config:/config \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push.outputs.image-digest }}
        
        # Wait for container to start
        sleep 30
        
        # Test health endpoint
        curl -f http://localhost:8888/api/health
        
        # Test setup page
        curl -f http://localhost:8888/setup
        
        # Clean up
        docker stop boxarr-test
        


  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-and-push, security-scan, test-deployment]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate changelog (basic implementation)
        echo "## What's Changed" > CHANGELOG.tmp
        git log --pretty=format:"* %s (%h)" $(git describe --tags --abbrev=0 HEAD~1)..HEAD >> CHANGELOG.tmp
        
        echo "## Docker Images" >> CHANGELOG.tmp
        echo "- \`ghcr.io/${{ github.repository }}:$VERSION\`" >> CHANGELOG.tmp
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.changelog.outputs.version }}
        body_path: CHANGELOG.tmp
        draft: false
        prerelease: false
        generate_release_notes: true
        
  notification:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [build-and-push, test-deployment]
    if: always()
    
    steps:
    - name: Notify on success
      if: needs.build-and-push.result == 'success' && needs.test-deployment.result == 'success'
      run: |
        echo "✅ Docker images built and published successfully!"
        echo "🚀 Images available at:"
        echo "${{ needs.build-and-push.outputs.image-tags }}"
        
    - name: Notify on failure
      if: needs.build-and-push.result == 'failure' || needs.test-deployment.result == 'failure'
      run: |
        echo "❌ Docker build or deployment failed!"
        exit 1